### ISSUE TITLE
Next.js API routes support?

### ISSUE THREAD

**Issue by servo1x** [fastify/fastify-nextjs#89]
## 🐛 Bug Report

We're not able to render next.js api routes, as described here: https://nextjs.org/docs/api-routes/introduction

## To Reproduce

```js
// pages/api/example.js

export default (req, res) => {
  res.statusCode = 200
  res.setHeader('Content-Type', 'application/json')
  res.end(JSON.stringify({ test: true }))
}
```

```js
// server.js

const path = require('path')
const nextConfig = require.resolve('./next.config')

const fastify = require('fastify')({
  logger: true,
  ignoreTrailingSlash: true,
})

fastify
  .register(require('fastify-cookie'))
  .register(require('fastify-nextjs'), { dev: false, dir: __dirname, conf: nextConfig })
  .register(require('fastify-static'), {
    root: path.join(__dirname, 'public'),

    maxAge: '365d',
    immutable: true,
    cacheControl: true,
  })
  .after(() => {
    fastify.next('/api/*')
  })

```

```js
// next.config.js
const withImages = require('next-images')

module.exports = withImages({
  assetPrefix: '',
  webpack(config, options) {
    return config
  }
})
```

```js
{"level":30,"time":1591260316508,"pid":65946,"hostname":"dev001","reqId":1,"req":{"method":"GET","url":"/api/example","hostname":"localhost:3000","remoteAddress":"127.0.0.1","remotePort":53206},"msg":"incoming request","v":1}
Could not find files for /api/example in .next/build-manifest.json
TypeError: res.setHeader is not a function
    at module.exports.6Rh6.__webpack_exports__.default (/Users/dev001/workspace/app/.next/server/static/AE6ko8zfA0RfswT5Q88B0/pages/api/maintenance.js:115:7)
    at d (/Users/dev001/workspace/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:498)
    at Za (/Users/dev001/workspace/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:39:16)
    at a.b.render (/Users/dev001/workspace/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:476)
    at a.b.read (/Users/dev001/workspace/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:18)
    at renderToString (/Users/dev001/workspace/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:54:364)
    at render (/Users/dev001/workspace/app/node_modules/next/dist/next-server/server/render.js:82:16)
    at Object.renderPage (/Users/dev001/workspace/app/node_modules/next/dist/next-server/server/render.js:323:20)
    at /Users/dev001/workspace/app/.next/server/static/AE6ko8zfA0RfswT5Q88B0/pages/_document.js:2369:21
    at Generator.next (<anonymous>)
{"level":30,"time":1591260316585,"pid":65946,"hostname":"dev001","reqId":1,"res":{"statusCode":500},"responseTime":75.81719696521759,"msg":"request completed","v":1}
```

## Expected behavior

API routes should return valid json.

## Your Environment

- *node version*: 12
- *fastify version*: 2.11.0
- *os*: Mac

## Workaround

Define API routes in fastify, but it would be preferred if we could do it in next.js.

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by daofresh** [comment]
I think this plugin should simply wrap the requests and redirect them to the Next handler, which will avoid problems.

**Comment by mcollina** [comment]
> I think this plugin should simply wrap the requests and redirect them to the Next handler, which will avoid problems.

Which it's what it is doing.

**Comment by heisonyee** [comment]
Red the guide [https://nextjs.org/docs/api-routes/api-middlewares#custom-config](url), try to add 

```
export const config = {
  api: {
    externalResolver: true,
  },
}
```
in  your /api/example.js, maybe, it will help, have a try.
